kind: pipeline
type: docker
name: default

steps:
  - name: test1
    image: 192.168.100.12:5000/alpine/docker:latest
    commands:
    - echo this should pass
  
  
  - name: test2
    image: 192.168.100.12:5000/alpine/docker:latest
    resources:
      requests:
        cpu: 6
        memory: 250MiB
      limits:
        cpu: 6
        memory: 500MiB
    commands:
    - echo this should fail
    - sleep 1000
    - exit 2

  - name: test3
    image: 192.168.100.12:5000/alpine/docker:latest
    commands:
    - echo stage status is $DRONE_STAGE_STATUS
    - echo build status is $DRONE_BUILD_STATUS
    when:
      status:
      - success
      - failure
