kind: pipeline
type: docker

workspace:
  path: /go/src/github.com/smartmore/SMore-Seg #设置工作目录，后续每个step都会在此目录下执行

steps:
  - name: build-dev #开发环境编译与单元测试
    image: 192.168.100.12:5000/deepmodels/product_base:latest
    environment:
      DRONE: "true" #设置环境变量
    settings:
      username:
        from_secret: username
      password:
        from_secret: password
    commands: #当前step执行的命令
      - git log --pretty=format:'%h' -n 1 > .tags
      - cat .tags
    when:
      event:
        - push
        - pull_request
      branch:
        - main

  - name: docker-dev #编译开发环境镜像
    image: 192.168.100.21:5000/plugins/docker:latest
    volumes: #在volume中创建临时文件夹
      - name: cache
        path: /cache
    settings:
      username:
        from_secret: username
      password:
        from_secret: password
      registry: 192.168.100.21:5000 #镜像仓库
      repo: 192.168.100.21:5000/deepmodels/segmentation #镜像名根据开发环境做区分或者后面版本号区分后面就不需要单独部署了
      dockerfile: Dockerfile.drone #编译镜像的Dockerfile
      insecure: true
    when:
      event:
        - push
      branch:
        - main

  - name: build-tag
    image: 192.168.100.12:5000/deepmodels/product_base:latest
    environment:
      DRONE: "true" #设置环境变量
    commands: #当前step执行的命令
      - echo $DRONE_TAG > .tags
      - cat .tags
    when:
      branch:
        - main
      event:
        - tag

  - name: docker-tag #编译测试环境镜像
    image: 192.168.100.12:5000/plugins/docker:latest
    volumes: #在volume中创建临时文件夹
      - name: cache
        path: /cache
    settings:
      username:
        from_secret: username
      password:
        from_secret: password
      registry: 192.168.100.21:5000 #镜像仓库
      repo: 192.168.100.21:5000/deepmodels/segmentation #镜像名
      dockerfile: Dockerfile.drone #编译镜像的Dockerfile
      insecure: true
    when:
      branch:
        - main
      event:
        - tag


volumes: #临时目录用于step之间文件共享，pipline结束自动销毁
  - name: cache
    temp: {}

trigger:
  branch:
    - main

image_pull_secrets:
  - dockerconfigjson
